travis:
  secure:
    BINSTAR_TOKEN: E5x8uAwQWDKqMed3DP/Wkpys9sWCz/OQaM22Iz3d9/dQRROnoM6Dp6EE71jUhLsKAi5k8SWaT0RlNS6nqu3GU/7740XfNla477oza5PQGz7yA94+nZ7m90732tr8+8mOn3sMnzVSLwTbIcf+dVw+mL6CTXfsxuHiwxz7u/GM+5zw91lPc5fOmJE2777YgBXfkqRRj4faXiBRaiG3EUdt7osdYHLOc0Na61zVlbyGek9CC5h4Np45Q6oeqoj6bPqGEt/g/WNXAg2vprODV2uKcf5Lej81ztRjqtsyqHvqdevPp9GOv0YdqvxMTTuomuVYvHb3s0MI9beAxA6M3MkgduN8DUo533v518/x9WAoU8U7zj3YWUKbDQCtGRevSaAC82dchszeEgK7fQ//uaabi9o34QAoVbUQg04uqe4QkKiIPR/pHz014r0JbBdWCvKAkCB/o57YZ03ORHoLOS5wVN59nNV+J3BRCswPfYDYaUFjT2gzJtWHbywmg9zyogUKs8E4uQJYgoYepaus52ckD6z0JRk3dbs42cpcGz8LqfO07vWeLibEM8EMPSpNEDOGsFzP5w4H8UysbP3hGir1Rg3uieJi4TAhgx3KHoY+0JVqLNKA3pk1iq5ppg7ZbMLUOuq4oR5JG0ZZlL78NxccBHm+xFu1bxSVrwNTOHiGs0k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
